#!/bin/python
import primefac
import sys
"""
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors
https://blog.professorferretto.com.br/como-determinar-a-quantidade-de-divisores-de-um-numero/
"""
n = 1
def NthTriangleNumber(order):
	return sum(range(1,order+1))
def NofDivisors(n):
	count = 1;
	fatr = list(primefac.primefac(n)) # contem repeat
	sfatr = set(fatr) # eliminou repeat
	for i in sfatr:
		count =  count * (fatr.count(i)+1)
	return count
while(NofDivisors(NthTriangleNumber(n))<=500):
	n+=1
print(NthTriangleNumber(n))
#print(NofDivisors(28)
